name = "ec2-network-monitor"
main = "src/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
AWS_REGION = "ap-northeast-1"  # 请根据实际情况修改
EC2_INSTANCE_ID = "i-0dff295491a246b51"      # 请填入您的 EC2 实例 ID
PUSH_CHANNEL = "1"
GOTIFY_URL= "https://gotify.liuq.pro/message"

# 以下变量需要在 Cloudflare Workers 的环境变量中设置
# AWS_ACCESS_KEY_ID
# AWS_SECRET_ACCESS_KEY 

[observability.logs]
enabled = false